import Head from "next/head";
import SignInCard from "../app/pages/signIn/signInForm";


export default function Home() {
  return (
    <>
      <Head>
        <title>INTO AEC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <SignInCard/>
      </main>
    </>
  );
}
