import React from "react";
import CreateLeadForm from "../../../app/pages/lead/create/createLeadMultistepForm";
import Head from "next/head";
import { ThemeProvider } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>INTO AEC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeProvider theme={{}}>
        <CreateLeadForm />
        </ThemeProvider>
      </main>
    </>
  );
}
